### ISSUE TITLE
Write one-page doc

### ISSUE THREAD

**Issue by dougb5** [jonahfried/spruce#15]
- Paragraph explaining why and how to use it
- Paragraph explaining how it works  (Doug to draft)
- Screenshot with compelling example(s)

I suggest actually putting this directly in popup.html.   It might be a hidden div that becomes visible when the "?" button is clicked.   I think it should be visible by default actually, unless a query has been made.

We should add OpenGraph tags (see https://ogp.me/) to popup.html so that it can be shared on social media.

**Comment by jonahfried** [comment]
I added some more detailed help when the help button is pressed as you suggested (still hidden by default) along with some gifs that I think show off usage pretty nicely.

**Comment by dougb5** [comment]
Oh I reeeeaally like the screen-recording GIFs (is there a better word for them? :))   Thanks for adding that.

The specific examples of searches don't show good results, in my opinion, so don't show this in the best light.   
May I suggest we pick from an essay of some sort?   So far I've found that essays / expository text have a higher hit rate for producing interesting results.

For example, here's an essay about fear of failure that Paul Graham (a silicon valley celebrity) wrote today.   I think using the first sentence as the example for the typed-in sentence, and the first paragraph for the context-menu example, work well!    http://paulgraham.com/early.html

**Comment by jonahfried** [comment]
New gifs are up on README and help page!

**Comment by dougb5** [comment]
Looks great, thanks!

**Comment by dougb5** [comment]
Re-opening as I forgot we need opengraph meta tags -- see link above.

Use "website" as the og:type value.

How about this for a description  (og:description meta field)   -- feel free to spruce up :)


Spruce is a search engine for inspiring sentences.  Tell Spruce about something you've read or written and it will find quotations or lyrics that are related to the subject matter, sometimes in surprising and subtle ways.  Spruce gives you a diverse set of perspectives on your text that you can cite in your work or reflect upon in your brainstorming.

**Comment by jonahfried** [comment]
Do we know what the url for Spruce will be? the og:url field is required

**Comment by dougb5** [comment]
How about I host it at   https://onelook.com/spruce/  ?

**Comment by jonahfried** [comment]
I think that all the necessary og tags are now present

**Comment by dougb5** [comment]
add margins
