### ISSUE TITLE
Ensure popup.html looks ok on mobile

### ISSUE THREAD

**Issue by dougb5** [jonahfried/spruce#16]
While the Chrome extension itself can't be installed on mobile Chrome (I think?), I still want the web page to be usable for smartphone users, since I plan to link to a copy of it for people to try out.     Can you ensure it looks and functions okay (for typed-in searches) on mobile? 

I think the viewport setting may need to be set  (not sure how relevant this still is in 2020 though, maybe there's a better way now?)
https://www.w3schools.com/css/css_rwd_viewport.asp

**Comment by jonahfried** [comment]
It looks good to me using the chrome mobile view. Bootstrap apparently tries pretty hard to make things mobile compatible, which is nice.

**Comment by jonahfried** [comment]
I'll close for now, but try to keep an eye on mobile stuff moving forward
