### ISSUE TITLE
sort similar not working on some clicks

### ISSUE THREAD

**Issue by jonahfried** [jonahfried/spruce#34]

**Comment by dougb5** [comment]
We determined that clicks on the SVG icon itself are not triggering the click handler that is attached to its parent div.

**Comment by dougb5** [comment]
fixed in https://github.com/jonahfried/spruce/commit/e029f23aa14b437d367777f473d824999ceaa9e5
@jonahfried FYI see https://javascript.info/bubbling-and-capturing for an explanation
