### ISSUE TITLE
Allow toggle to sort by relevance (default) or complexity

### ISSUE THREAD

**Issue by dougb5** [jonahfried/spruce#4]

**Comment by dougb5** [comment]
Thanks Jonah!  I tried the extension that's in the branch now and I like the new options to sort by complexity / suitabilities.   Sentence length works well enough for launch as a measure of complexity, but maybe we can add a more principled measure (based on the parse?) in the future to the backend.

I think it's unlikely anyone would want to sort ascending by suitability (least relevant first).  And in hindsight, I now see that with two sort toggles, it's a little hard for the user to see what the current state is.    How about, instead of two different sort toggles exposed, we have a bar of three radio buttons, one of which is always highlighted:      "Most relevant"    "Simplest"    "Most complex".       

"Most relevant" sorts ascending by suitability,  "Simplest" sorts ascending by sentence length, and "Most complex" sorts descending by sentence length.  

By default after any query, "Most relevant" is selected.

See radio buttons on
https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons

Does this sound good?

**Comment by jonahfried** [comment]
That should do it :)

Let me know if there should be any more tweaks

**Comment by dougb5** [comment]
Explore using bootstrap-style radio for sort options.  Reword (done?).   Explore bootstrap-style for corpus selector too.

**Comment by dougb5** [comment]
Looks good now!
